Insert into COUNTRY_MASTER (COUNTRY_ID,COUNTRY_NAME) VALUES (1,'INDIA');
INSERT INTO COUNTRY_MASTER (COUNTRY_ID,COUNTRY_NAME) VALUES (2,'USA');




INSERT INTO STATE_MASTER (STATE_ID,STATE_NAME,COUNTRY_ID) VALUES (1,'GUJARAT',1);
INSERT INTO STATE_MASTER (STATE_ID,STATE_NAME,COUNTRY_ID) VALUES (2,'MAHARASTRA',1);
INSERT INTO STATE_MASTER (STATE_ID,STATE_NAME,COUNTRY_ID) VALUES (3,'NEW JERSEY',2);
INSERT INTO STATE_MASTER (STATE_ID,STATE_NAME,COUNTRY_ID) VALUES (4,'PENNSYLVANIA',2);





INSERT INTO CITY_MASTER (CITY_ID,CITY_NAME,STATE_ID) VALUES (1,'AHMEDABAD',1);
INSERT INTO CITY_MASTER (CITY_ID,CITY_NAME,STATE_ID) VALUES (2,'SURAT',1);
INSERT INTO CITY_MASTER (CITY_ID,CITY_NAME,STATE_ID) VALUES (3,'MUMBAI',2);
INSERT INTO CITY_MASTER (CITY_ID,CITY_NAME,STATE_ID) VALUES (4,'PUNE',2);
INSERT INTO CITY_MASTER (CITY_ID,CITY_NAME,STATE_ID) VALUES (5,'JERSEY CITY',3);
INSERT INTO CITY_MASTER (CITY_ID,CITY_NAME,STATE_ID) VALUES (6,'EAGLEWOOD',3);
INSERT INTO CITY_MASTER (CITY_ID,CITY_NAME,STATE_ID) VALUES (7,'PHILADELPHIA',4);
INSERT INTO CITY_MASTER (CITY_ID,CITY_NAME,STATE_ID) VALUES (8,'WILKES-BARRE',4);
INSERT INTO CITY_MASTER (CITY_ID,CITY_NAME,STATE_ID) VALUES (9,'VADODARA',1);
INSERT INTO CITY_MASTER (CITY_ID,CITY_NAME,STATE_ID) VALUES (10,'SCRANTON',4);